### ISSUE TITLE
Hello Good sir im in some need of help

### ISSUE THREAD

**Issue by ghost** [krishpranav/rb-sqlscanner#1]
( Im Extremly new to using ruby for please forgive me if its a stupid thing to ask for help about )

Traceback (most recent call last):
	5: from sqlscanner.rb:2:in `<main>'
	4: from sqlscanner.rb:2:in `require_relative'
	3: from /home//Desktop/rb-sqlscanner-master/lib/imports/constants_and_requires.rb:22:in `<top (required)>'
	2: from /home//Desktop/rb-sqlscanner-master/lib/imports/constants_and_requires.rb:22:in `require_relative'
	1: from /home//Desktop/rb-sqlscanner-master/lib/misc/banner.rb:3:in `<top (required)>'
/home//Desktop/rb-sqlscanner-master/lib/misc/banner.rb:3:in `require_relative': /home//Desktop/rb-sqlscanner-master/lib/modules/core/settings.rb:21: syntax error, unexpected '=', expecting `end' (SyntaxError)
  =begin
  ^
/home//Desktop/rb-sqlscanner-master/lib/modules/core/settings.rb:34: syntax error, unexpected '=', expecting `end'
  =end
  ^
/home//Desktop/rb-sqlscanner-master/lib/modules/core/settings.rb:225: syntax error, unexpected end-of-input, expecting `end'

**Comment by ghost** [comment]
NVM Its just white widow SRC i was able to fix it

**Comment by krishpranav** [comment]
sorry for the late reply i just saw your issue how you fixed it
